RI-29: sauvegarde les informations personnelles dans la BD
dyno-nuggets/refonte-implicaction pull request #105
Opened 2021-09-25 21:53 UTC by dylanbrudey

Permet de sauvegarder les informations du profil d'un utilisateur (_Job Seeker_ ou _Recruiter_) dans la base de données.

2021-09-25 21:56 UTC, dylanbrudey commented
Si quelqu'un veut changer les noms de personal Info, personal card... c'est le moment !

2021-09-26 13:13 UTC, matthieuaudemard requested changes
C'est cool t'as bien compris le mécanisme 😉 Juste quelques petites modifs et tu pourras merge 👍

2021-09-26 13:13 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/UserService.java
> +        User userUpdate = userRepository.save(user);
Plutôt que de setter ces champs ici je pense qu'il vaut mieux les ajouter dans l'adapter s'il n'y sont pas déjà et/ou dans le user.ts

2021-09-26 15:31 UTC, matthieuaudemard requested changes

2021-09-26 15:31 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/UserService.java
> +        User user = userAdapter.toModel(userDto);
tu peux directement setter les champs de databaseUser à l'aide des champs de ton dto sans passer par l'adapter.

2021-09-26 15:32 UTC, matthieuaudemard approved these changes
🍾

2021-09-26 15:33 UTC, merged