RI-62: ajoute/modifie/supprime une formation depuis la page de profil
dyno-nuggets/refonte-implicaction pull request #108
Opened 2021-09-28 23:08 UTC by matthieuaudemard

* ajout des méthodes en back
 * déplacement des méthodes des expériences vers le controller d'experience
 * renommage des classes css 'hover-theme' en 'theme-on-hover'

2021-09-30 16:34 UTC, PaFlu-SDV requested changes

2021-09-30 16:34 UTC, PaFlu-SDV commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/ExperienceController.java
> +    public ResponseEntity<WorkExperienceDto> createTraining(@RequestBody final WorkExperienceDto experienceDto) {
Peut etre rename createTraining en createExperience et pareil pour update

2021-09-30 23:39 UTC, matthieuaudemard commented on frontend-implicaction/src/app/app.component.scss
> +}
à supprimer

2021-09-30 23:39 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.html
> +      class="cursor-pointer me-xl-2 secondary-on-hover oscillate-on-hover"
enlever la classe oscillate-on-hover

2021-09-30 23:39 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.ts
>    deleteEmitter = new EventEmitter<WorkExperience>();
supprimer ces lignes et répercuter ce changement dans le composant parent

2021-09-30 23:39 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.ts
> +        () => {
ajouter un commentaire pour dire pq c'est vide

2021-09-30 23:39 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/training-detail/training-detail.component.ts
> +  readonly yearRange = `1900:${new Date().getFullYear() + 1}`;
constante en haut

2021-09-30 23:39 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/training-detail/training-detail.component.ts
> +        () => {
commentaire pour dire pourquoi c'est vide

2021-09-30 23:39 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/training-form/training-form.component.html
> +      [ngClass]="{'ng-invalid ng-touched': (isSubmitted || formTraining.controls['label'].touched) && formTraining.controls['label'].errors}"
voir avec l'attribut dirty comme dans l'exemple : 
```typescript
<input type="text" id="name" name="name" class="form-control"
      required minlength="4" appForbiddenName="bob"
      [(ngModel)]="hero.name" #name="ngModel">

<div *ngIf="name.invalid && (name.dirty || name.touched)"
    class="alert">

  <div *ngIf="name.errors?.required">
    Name is required.
  </div>
  <div *ngIf="name.errors?.minlength">
    Name must be at least 4 characters long.
  </div>
  <div *ngIf="name.errors?.forbiddenName">
    Name cannot be Bob.
  </div>

</div>
```
https://angular.io/guide/form-validation

2021-09-30 23:39 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/training-form/training-form.component.ts
> +    let training$: Observable<WorkExperience>;
```suggestion
    let training$: Observable<Training>;
```

2021-09-30 23:39 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/training-form/training-form.component.ts
> +      trainingFromDb => {
trainingUpdate

2021-09-30 23:39 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/training-form/training-form.component.ts
> +  private initForm(training: Training): void {
rendre training facultatif

2021-09-30 23:39 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/user-profile/user-profile.component.ts
>    user: User = {};
```suggestion
  user = {} as User;
```
voir si c'est pas mieux

2021-10-01 19:33 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/training-form/training-form.component.html
> +      [ngClass]="{'ng-invalid ng-touched': (isSubmitted || formTraining.controls['label'].touched) && formTraining.controls['label'].errors}"
Créer une fiche plutôt pour ça

2021-10-01 20:04 UTC, merged