RI-136: Archivage d'un job
dyno-nuggets/refonte-implicaction pull request #167
Opened 2021-11-09 22:15 UTC by mathusha-sdv

* tests

2021-11-10 18:59 UTC, mathusha-sdv commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +                .andExpect(jsonPath("$.status.label", is(jobPostingDtoArchived.getStatus().getLabel())));
Je compare le label pcq il attend un long 2L et le résultat est 2

2021-11-10 19:00 UTC, mathusha-sdv commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/StatusRepository.java
> +    @Query("select s from Status s " +
pas optimisé, il faudrait un enum ?

2021-11-11 05:56 UTC, matthieuaudemard requested changes
J'ai proposé une simplification en passant par le champ `archive` du modèle Job.

Il faudrait que tu délimites tes tests comme je l'ai fait en mode

```java
// given
...
// when
...
// then
```
pour plus de lisibilité, sinon c'est vite le bordel 😆 

Mais gg quand même et merci pour les test 👍

2021-11-11 05:56 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/JobPostingController.java
> +    public ResponseEntity<JobPostingDto> archive(@PathVariable Long jobId) {
```suggestion
    public ResponseEntity<JobPostingDto> toggleArchive(@PathVariable Long jobId) {
```

2021-11-11 05:56 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/StatusRepository.java
> +    @Query("select s from Status s " +
En fait on va faire autrement, tu peux supprimer ces 2 méthodes

2021-11-11 05:56 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/JobPostingService.java
> +    public JobPostingDto archiveOrUnarchiveJobPosting(Long jobPostingId) {
```suggestion
    public JobPostingDto toggleArchive(Long jobPostingId) {
```

2021-11-11 05:56 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/JobPostingService.java
> +                .orElseThrow(() -> new NotFoundException("Impossible de supprimer l'offre, " + jobPostingId + " n'existe pas."));
La classe message a été créée pour stocker ce genre de message. Tu peux créer une constante dans cette classe stp ? De plus attention à ton copier coller, tu cherches pas à supprimer une offre ;)

```suggestion
                .orElseThrow(() -> new NotFoundException(String.format(Message.JOB_NOT_FOUND, jobId)));
```

2021-11-11 05:56 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/JobPostingService.java
> +        return jobPostingAdapter.toDto(save);
l'idée c'est d'introduire dans le modèle JobPosting (et du coup dans le dto) un attribut booleen `archive` pour au final simplifier la méthode comme ceci : 
```suggestion
       jobPosting.isArchive(!jobPosting.isArchive())
        final JobPosting save = jobPostingRepository.save(jobPosting);
        return jobPostingAdapter.toDto(save);
```

2021-11-11 05:56 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +                .andExpect(jsonPath("$.id", is(Math.toIntExact(jobPostingDtoAvailable.getId()))))
En fait j'me suis aperçu que tu pouvais simplifier comme ça : 
```suggestion
                .andExpect(jsonPath("$.id", is((jobPostingDtoAvailable.getId().intValue())))
```
https://docs.oracle.com/javase/7/docs/api/java/lang/Long.html#intValue()

2021-11-11 05:56 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +                .andExpect(jsonPath("$.status.label", is(jobPostingDtoArchived.getStatus().getLabel())));
En appliquant ma modif tu aurais juste à vérifier que :
```suggestion
                .andExpect(jsonPath("$.archive", is(jobPostingDtoArchived.isArchive())));
```

2021-11-11 05:56 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +    StatusDto statusArchived;
🗑️

2021-11-11 05:56 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +        statusArchived = StatusDto.builder().id(2L).label("jobArchived").type("job_posting").build();
🗑️

2021-11-11 05:56 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +        mvc.perform(patch(JOBS_BASE_URI + ARCHIVE_JOB_URI, jobPostingDtoAvailable.getId()).contentType(APPLICATION_JSON)).andDo(print())
```suggestion
        mvc.perform(patch(JOBS_BASE_URI + ARCHIVE_JOB_URI, jobPostingDtoAvailable.getId()).contentType(APPLICATION_JSON))
        .andDo(print())
```

2021-11-11 05:56 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +    void archiveJobShouldChangeStatus() throws Exception {
J'essaye de structurer mes tests en 3 sections : 
 * given
 * when
 * then

tu peux t'inspirer par exemple du SubredditControllerIntegrationTest, ça permet de rendre le truc plus compréhensible

2021-11-11 05:56 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +        given(jobPostingService.archiveOrUnarchiveJobPosting(jobPostingDtoAvailable.getId())).willReturn(jobPostingDtoArchived);
```suggestion
        given(jobPostingService.archiveOrUnarchiveJobPosting(anyLong())).willReturn(expectedDto);
```
En fait on s'en fiche de la valeur de l'id en paramètre. On veut juste que  ça nous retourne quelque chose donc c'est le `willReturn()` qui compte

2021-11-11 05:56 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +                .build();
tu peux simplifier en ne créant qu'un seul dto et en ne valuant qu'un minimum de champs genre id et archive. 

```suggestion
        JobPostingDto expectingDto = JobPostingDto.builder()
                .id(1L)
                .archive(true)
                .build();
```

2021-11-11 05:56 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +                .andExpect(jsonPath("$.salary", is(jobPostingDtoAvailable.getSalary())))
🧹  => 🗑️

2021-11-11 05:56 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +        verify(jobPostingService, times(0)).archiveOrUnarchiveJobPosting(anyLong());
```suggestion
        verify(jobPostingService, never()).archiveOrUnarchiveJobPosting(anyLong());
```

Je sais que j'ai mis `times(0)` au début, mais `never()` c'est mieux 😉

2021-11-11 05:56 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/StatusRepository.java
> +    Status getUnarchivedStatus();
avec ma simplification on n'a plus besoin de ces méthodes -> 🗑️

2021-11-14 18:10 UTC, mathusha-sdv commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/JobPostingService.java
> +        return jobPostingAdapter.toDto(save);
du coup ce serait un champ persisté en base ? ou un champ propre à l'entité ?

2021-11-14 18:41 UTC, mathusha-sdv commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/JobPostingService.java
> +        return jobPostingAdapter.toDto(save);
et en ce qui concerne le champ status, on en fait quoi ?

2021-11-15 05:00 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/JobPostingController.java
> +    }
🎉  c'est quand même plus simple 😄

2021-11-15 05:01 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/JobPostingDto.java
>      private StatusDto status;
Je pense qu'on peut même supprimer cet attribut si on s'en sert pas ailleurs ?

2021-11-15 05:02 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/JobPostingService.java
> +    }
🎉 dsl mais j'aime vraiment quand c'est propre 🥳

2021-11-15 05:16 UTC, matthieuaudemard requested changes
Super 👍 
 * les tests sont très bien (j'ai juste laissé une petite remarque pour une amélioration et un peu de code style à corriger)
 * le périmètre est super géré 🥳 et c'est un plaisir de corriger un petite PR comme ça 

![image](https://user-images.githubusercontent.com/4210719/141726315-870e72e0-1a33-4abf-b9e3-ef8393863e4d.png)

2021-11-15 05:16 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +        //given
please please please :
```java
// il faut tjs mettre un espace entre les '//' et le premier mot de ton commentaire
```
🥺 🙏

2021-11-15 05:16 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +        //when
espace

2021-11-15 05:16 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +        //then
espace

2021-11-15 05:16 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +                .andExpect(jsonPath("$.archive", is(expectedDto.isArchive())));
ça serait peut être plus logique de vérifier que `$.archive` est l'inverse de `givenDto.isArchive()` nan ? et comme du coup tu n'utilises plus `expectedDto`, tu pourrais supprimer cette variable.

On gagnerait en :
 * lisibilité (moins de code à lire)
 * et en logique, parce qu'on veut vérifier au final que `archive` est l'opposé de ce qu'on lui a donné à la base
```suggestion
                .andExpect(jsonPath("$.archive", is(!givenDto.isArchive())));
```

2021-11-15 05:16 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +        //given
espace

2021-11-15 05:16 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +        //when
espace

2021-11-15 05:16 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +        //then
espace

2021-11-15 05:16 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +        //given
espace

2021-11-15 05:16 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +        //when
espace

2021-11-15 05:16 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +        //then
espace

2021-11-15 05:16 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +        resultActions.andExpect(status().isForbidden());
tu peux chaîner les méthodes : 
```suggestion
        resultActions.andDo(print())
            .andExpect(status().isForbidden());
```

2021-11-15 05:16 UTC, matthieuaudemard commented on data.sql
> +    ADD COLUMN `archive` tinyint(1) NULL DEFAULT '0' AFTER `created_at`;
C'est pas une mauvaise chose de le mettre, mais par défaut spring va créer le champs automatiquement si il n'existe pas en checkant tous les modèles lors du lancement de l'application

2021-11-15 10:40 UTC, matthieuaudemard requested changes

2021-11-15 10:40 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/JobPostingDto.java
> +    private boolean isArchive;
tu peux l'appeler `archive`stp. lombock qu'on utilise pour la génération des getters et setters va générer une méthode qu'il va nommer 'is' + 'nom de l'attribut' dans le cas d'un attribut de type booléen ... ça fait bizarre du coup d'avoir un jobPostingDto.isIsArchive().

```suggestion
    private boolean archive;
```

2021-11-15 10:40 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/JobPosting.java
> +    private boolean isArchive;
idem : 
```suggestion
    private boolean archive;
```

2021-11-16 12:38 UTC, matthieuaudemard approved these changes

2021-11-16 13:00 UTC, merged