RI-112: filtrage d'une offre
dyno-nuggets/refonte-implicaction pull request #168
Opened 2021-11-10 22:48 UTC by mathusha-sdv

![112](https://user-images.githubusercontent.com/85649177/141206029-bfbe5caf-f95b-4e88-b509-e1d285f8bc91.gif)
* Filtrage sur le nom et la description de la compagnie
* Ajout d'une route en back pour récupérer les compagnies avec critères

2021-11-11 05:11 UTC, matthieuaudemard requested changes
Super boulot 👍 J'ai laissé quelques commentaires mais c'est vraiment top 🍾 .

Est-ce que tu pourrais ajouter plusieurs compagnies pour vérifier que la pagination fonctionne bien stp ?

D'autre part, c'est peut être préférable de lancer la recherche quand l'utilisateur appuie sur `enter` parce que ça lance une requête à chaque caractère entré ... potentiellement ça peut faire bcp .... perso ça arrive à mon chat de s'assoir sur mon clavier ce qui me laisse parfois des messages de centaines de caractères 🤣 imagine le truc ...

![](https://static.mmzstatic.com/wp-content/uploads/2014/08/Cristina-gif.gif)

2021-11-11 05:11 UTC, matthieuaudemard commented on frontend-implicaction/src/app/core/services/api-endpoints.service.ts
> +    };
Comme au dessus on va répéter ce code très souvent potentiellement. Tu pourrais en faire une méthode privée stp ? (⚠️ `ctrl-alt-m`je crois sur windows ou alors tu sélectionnes le bout de code à mettre dans la méthode, clic-droit -> refactor -> extract methode)

```suggestion
    // quelque chose dans ce goût là ...
    const objectParam = concatCriterias(criteria, pageable);
```

2021-11-11 05:11 UTC, matthieuaudemard commented on frontend-implicaction/src/app/core/services/api-endpoints.service.ts
> +      });
```suggestion
      (qs: QueryStringParameters) => this.buildQueryStringFromFilters(objectParam, qs)
  );
```

Si je dis pas de bétise ça doit fonctionner

2021-11-11 05:22 UTC, matthieuaudemard requested changes

2021-11-11 05:22 UTC, matthieuaudemard commented on frontend-implicaction/src/app/shared/components/company-filter/company-filter.component.html
> +      <label class="form-label text-dark fw-bold" for="nameInput">Nom de la compagnie</label>
```suggestion
      <label class="form-label text-dark fw-bold" for="keywordInput">Rechercher</label>
```
ou un truc comme ça

2021-11-11 05:22 UTC, matthieuaudemard commented on frontend-implicaction/src/app/job/models/company-criteria-filter.ts
> +  name?: string;
remplacer `name` par `keyword` (⚠️ shitf+f6-> 🤟 )

2021-11-11 05:22 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/CompanyController.java
> +        Page<CompanyDto> companyDtos = companyService.findAllWithCriteria(pageable, name);
Allez just for fun un p'tit test pour cette méthode 🧪

2021-11-14 17:33 UTC, mathusha-sdv commented on frontend-implicaction/src/app/admin/jobs/components/job-posting-form/job-posting-form.component.ts
> +import {CompanyService} from '../../../../company/services/company.service';
j'avais placé le company service au mauvais endroit T-T

2021-11-19 19:01 UTC, matthieuaudemard requested changes

2021-11-19 19:01 UTC, matthieuaudemard commented on frontend-implicaction/src/app/shared/components/job-filter/job-filter.component.html
> +        [(ngModel)]="criteria.search"
Hmmm j'ai rajouté ça pour tester mais je pense qu'on peut le supprimer

2021-11-19 20:49 UTC, mathusha-sdv commented on frontend-implicaction/src/app/company/enums/company-sort.enum.ts
> +
Il est utilisé pour le tri par nom de compagnie :)

2021-11-22 00:15 UTC, matthieuaudemard approved these changes

2021-11-22 19:47 UTC, merged