RI-150 : fusionne les méthodes create et update du CompanyController
dyno-nuggets/refonte-implicaction pull request #173
Opened 2021-11-13 15:39 UTC by dylanbrudey

2021-11-13 16:52 UTC, matthieuaudemard requested changes
Un p'tit TI sur cette méthode du controller et ça sera parfait 😉

2021-11-13 17:00 UTC, dylanbrudey commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/CompanyController.java
> +    public ResponseEntity<CompanyDto> createAndUpdate(@RequestBody CompanyDto companyDto) throws ImplicactionException {
En faisant comme ça, uniquement la première annotation est prise en compte.
Les autres modifs ont été faites parce que justement cette syntaxe ne fonctionnait pas. J'ai pas trouvé d'autres moyens qu'utiliser @RequestMapping par méthode : /

2021-11-13 21:28 UTC, dylanbrudey commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/CompanyController.java
> +    public ResponseEntity<CompanyDto> createAndUpdate(@RequestBody CompanyDto companyDto) throws ImplicactionException {
En conservant `@RequestMapping(COMPANIES_BASE_URI)` en annotation de classe ?
Oui, ça fonctionne aussi. Je fais comme ça si tu préfères 👍

2021-11-13 22:01 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/CompanyController.java
> +    public ResponseEntity<CompanyDto> createAndUpdate(@RequestBody CompanyDto companyDto) throws ImplicactionException {
oui c'est plus propre merci 👍

2021-11-18 22:20 UTC, matthieuaudemard approved these changes

2021-11-18 22:23 UTC, dylanbrudey commented
RI-150 : fusionne les méthodes create et update du CompanyController

2021-11-18 22:24 UTC, merged