Ri 137: selectionne plusieurs offres dans l'admin
dyno-nuggets/refonte-implicaction pull request #180
Opened 2021-11-15 14:28 UTC by M3L-DC

On peut maintenant sélectionner une ou plusieurs offres dans l'admin

![GIF 15-11-2021 15-24-08](https://user-images.githubusercontent.com/36151209/141798469-7f592e98-b022-431a-974c-7d06fc95e2eb.gif)

2021-11-15 14:41 UTC, M3L-DC commented on frontend-implicaction/src/app/admin/jobs/components/jobs-table/jobs-table.component.html
> +      <th class="text-wrap text-uppercase col-1 col-sm-2 col-lg-3" scope="col">Nom</th>
Il faut remettre le petit 3

2021-11-22 21:11 UTC, mathusha-sdv approved these changes

2021-11-22 21:14 UTC, mathusha-sdv reviewed
il te manque des trucs à faire encore ?

2021-11-22 22:36 UTC, matthieuaudemard requested changes

2021-11-22 22:36 UTC, matthieuaudemard commented on frontend-implicaction/src/app/admin/jobs/components/jobs-table/jobs-table.component.html
>  >
Il manque
```
<p-table
  [(selection)]="selectedJobs"
```

2021-11-25 22:01 UTC, matthieuaudemard approved these changes

2021-11-25 22:06 UTC, merged

2021-11-25 22:06 UTC, matthieuaudemard approved these changes