RI-139: Archive plusieurs offres
dyno-nuggets/refonte-implicaction pull request #184
Opened 2021-11-18 22:36 UTC by mathusha-sdv

J'ai fait des tests 
 j'ai modifié une partie que j'ai push au niveau de l'archivage (j'ai oublié un point d'exclamation dans le toggleArchive)

2021-11-19 00:12 UTC, matthieuaudemard requested changes
Il faudra :
 

- [ ] modifier le controller pour qu'il reçoive une liste de jobIds
- [ ] créer une méthode ds le service qui prend une liste de jobIds et change l'attribut archive de chaque élément
- [ ] mettre à jour les tests

2021-11-19 00:12 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +        List<JobPostingDto> givenDto = Arrays.asList(
```suggestion
        List<JobPostingDto> givenDto = Collections.singletonList(
```

2021-11-19 00:12 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +        List<JobPostingDto> expectedDto = Arrays.asList(
```suggestion
        List<JobPostingDto> expectedDto = Collections.singletonList(
```

2021-11-19 00:12 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +        Gson gson = new Gson();
JobsPostingControllerTest implémtente ControllerIntegrationTestBase qui intègre un attribut gson déjà donc 🧹

2021-11-19 00:12 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +            verify(jobPostingService, times(1)).toggleArchiveJobPosting(anyLong());
ça (times(1)) a ne marche que parce que tu as un seul élément dans ta liste.

Il faudra que tu changes ce test pour le mettre en accord avec la nouvelle méthode qui prend une liste de jobIds

2021-11-19 00:12 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +    }
Et le test si tu es pas authentifié ?

2021-11-19 23:35 UTC, mathusha-sdv commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +            verify(jobPostingService, times(1)).toggleArchiveJobPosting(anyLong());
Okay ça marche, par contre comme j'ai écris en haut, le test archiveJobShouldChangeListStatus ne fonctionne pas, quand j'envoie mes données, l'API me renvoie un body null. Du coup lav vérification sur les résultats ne fonctionne pas. Tu vois de quoi ça peut s'agir ?

2021-11-22 05:04 UTC, matthieuaudemard requested changes
Pas mal, j'ai laissé quelques commentaires qui devrait te permettre de faire passer les tests

2021-11-22 05:04 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +                    .andExpect(jsonPath(contentPath + ".id", is(job.getId())))
```suggestion
                    .andExpect(jsonPath(contentPath + ".id", is(job.getId().intValue())))
```
Le teste devrait échouer je pense parce qu'il essaye de comparer un int (`$[x].id`) à un long (`job.getId()`)

2021-11-22 05:04 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +                    .andExpect(jsonPath("$.archive", is(!job.isArchive())));
```suggestion
                    .andExpect(jsonPath(contentPath + ".archive", is(!job.isArchive())));
```

2021-11-22 05:04 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
> +            verify(jobPostingService, times(givenDto.size())).toggleArchiveAll(givenDto);
Je pense que dans ton exemple le résultat est bon, mais c'est parce que ta liste n'a qu'un seul élément.
```suggestion
            verify(jobPostingService, times(1)).toggleArchiveAll(givenDto);
```

2021-11-22 19:46 UTC, matthieuaudemard approved these changes

2021-11-22 20:26 UTC, merged