RI-41: [admin/job/front] permet d'archiver une offre depuis le listing des offres
dyno-nuggets/refonte-implicaction pull request #191
Opened 2021-11-21 20:48 UTC by mathusha-sdv

![41](https://user-images.githubusercontent.com/85649177/142778412-783a7e59-a4ec-4acd-a73d-690f906366b5.gif)

2021-11-22 00:18 UTC, matthieuaudemard requested changes
Ca serait vraiment génial si tu pouvais : 

1. merge la #168 
2. rebase
3. faire en sorte que JobsTableComponent extends de BaseWithPagination pour éviter de trop se répéter parce qu'actuellement on a 3 gros blocs de codes de JobsTableComponent qui sont répétés un peu partout ...

2021-11-22 00:18 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/JobPosting.java
> +    @Column(name = "archive", nullable = false, columnDefinition = "BOOLEAN")
```suggestion
    @Column(columnDefinition = "boolean default false")
```

2021-11-22 00:18 UTC, matthieuaudemard commented on frontend-implicaction/src/app/job/services/job.service.ts
> +    return this.http.patch(this.apiEndpointsService.archiveJobPostingEndpoint(jobPostingId), '');
```suggestion
    return this.http.patch(this.apiEndpointsService.archiveJobPostingEndpoint(jobPostingId), null);
```

2021-11-22 00:18 UTC, matthieuaudemard commented on frontend-implicaction/src/app/shared/enums/status.enum.ts
> +export enum StatusEnumCode {}
Si cette classe n'est pas utilisée dans le projet, peux-tu la supprimer stp ?

2021-11-24 02:13 UTC, matthieuaudemard commented on frontend-implicaction/src/app/admin/jobs/components/jobs-table/jobs-table.component.ts
> +  protected async getFilterFromQueryParams(): Promise<void> {
Ok ! Pour pas encore élargir le périmètre de cette Jira on va laisser comme ça, mais ça serait top si tu pouvais faire une petite Jira de refacto par la suite qui modifiera cette fonction dans la classe mère pour qu'elle prenne en paramètre le tableau `filterKeys` stp ? Ca nous évitera encore une fois de se répéter 👍

2021-11-27 18:24 UTC, mathusha-sdv commented on frontend-implicaction/src/app/admin/jobs/components/jobs-table/jobs-table.component.ts
> +  protected async getFilterFromQueryParams(): Promise<void> {
ça marche, c'est le ticket RI-199. Justement je ne voulais pas franchir ce périmètre :)

2021-11-28 08:58 UTC, matthieuaudemard reviewed
Je vois aucun changement sur ta PR par rapport à la dernière fois. C'est normal ?

2021-11-28 14:27 UTC, matthieuaudemard approved these changes

2021-11-28 14:37 UTC, merged