Ri-200 : Ajoute la page Espace Entreprise
dyno-nuggets/refonte-implicaction pull request #209
Opened 2021-12-05 21:37 UTC by M3L-DC

On peut maintenant accéder à la page Espace entreprise
![localhost_4200_entreprise](https://user-images.githubusercontent.com/36151209/144764253-f8f0b548-fc87-40aa-aeee-8c153b3b531b.png)

Il y a aussi la modification de l'image de la page d'accueil (RI-212)
![localhost_4200_](https://user-images.githubusercontent.com/36151209/144764272-68422b87-be25-46e9-b140-ddbd98f4f6b1.png)

2021-12-05 22:32 UTC, dylanbrudey reviewed
Nice, et très proche de la maquette ^^

2021-12-06 20:12 UTC, matthieuaudemard requested changes

2021-12-06 20:12 UTC, matthieuaudemard commented on frontend-implicaction/src/app/company/components/business-area/business-area.component.ts
> +export class BusinessAreaComponent implements OnInit {
```suggestion
export class BusinessAreaComponent {
```

2021-12-06 20:12 UTC, matthieuaudemard commented on frontend-implicaction/src/app/company/components/business-area/business-area.component.ts
> +  }
supprimer ces 2 méthodes qui sont du coup inutiles

2021-12-06 20:12 UTC, matthieuaudemard commented on frontend-implicaction/src/app/home/components/index/index.component.html
> +      <img alt="" class="img-fluid" src="assets/img/banner.jpg"/>
un p'tit alt des familles valué et un attribut par ligne stp

2021-12-06 20:12 UTC, matthieuaudemard commented on frontend-implicaction/src/app/home/components/index/index.component.html
> +          <img alt="reseau" class="img-fluid img-intro" src="assets/img/reseau.png">
un attribut par ligne stp

2021-12-06 20:12 UTC, matthieuaudemard commented on frontend-implicaction/src/app/home/components/index/index.component.html
> +          <img alt="dynamique" class="img-fluid img-intro" src="assets/img/dynamique.png">
un attribut par ligne stp

2021-12-06 20:12 UTC, matthieuaudemard commented on frontend-implicaction/src/app/home/components/index/index.component.html
> +          <img alt="forum" class="img-fluid img-intro" src="assets/img/forum.png">
un attribut par ligne stp

2021-12-07 16:39 UTC, matthieuaudemard requested changes
Juste une petite retouche, le reste est top 👍

2021-12-07 16:39 UTC, matthieuaudemard commented on frontend-implicaction/src/app/shared/components/header/header.component.html
> +        <img alt="implic'action" class="img-fluid" src="assets/img/logo_implic'action.png">
hmm j'suis pas fan des apostrophes dans les noms de fichier ! je sais jamais si ça va pas poser de problèmes en fonction du système ou autre, tu pourrais supprimer celle là du nom de l'image stp et mettre un attribut par ligne stp 😉

2021-12-09 21:53 UTC, matthieuaudemard approved these changes

2021-12-09 22:07 UTC, merged