RI-217: rejoint un groupe
dyno-nuggets/refonte-implicaction pull request #210
Opened 2021-12-06 20:05 UTC by mathusha-sdv

![217](https://user-images.githubusercontent.com/85649177/144914188-6fb35109-2ad8-43c3-9df5-c62dd478fe7a.gif)

C'est une premiere ebauche, j'ai commencé à travailler sur pouvoir rejoindre un groupe depuis une discussion mais jsp si c'est compris dans la jira --> la subtilité c'est que l'ajout à partir du listing des meilleurs groupe se fait via l'id, mais depuis une discussion je ne récupère que le nom du groupe. Est ce que je me base sur le nom du groupe pour le listing des top groupes ?

Il faudrait aussi voir le css du bouton d'ajout, j'ai pas trouvé mieux (faut pas trop me demander de front)

2021-12-07 16:46 UTC, matthieuaudemard commented
> Il faudrait aussi voir le css du bouton d'ajout, j'ai pas trouvé mieux (faut pas trop me demander de front)
Tu peux peut-être mettre juste un lien "rejoindre"

2021-12-07 19:36 UTC, mathusha-sdv commented
> 

dans ce cas là, si le nom de groupe est trop long ça ne sera pas très beau :/

> > Il faudrait aussi voir le css du bouton d'ajout, j'ai pas trouvé mieux (faut pas trop me demander de front)
> 
> Tu peux peut-être mettre juste un lien "rejoindre"

vu que le top group list est assez etroit, ça serait sur deux lignes donc je suis partie sur une icone

2021-12-09 20:41 UTC, matthieuaudemard requested changes
Quelques propositions, hésite pas si besoin

2021-12-09 20:41 UTC, matthieuaudemard commented on frontend-implicaction/src/app/core/services/api-endpoints.service.ts
> +    return ApiEndpointsService.createUrl(uri);
```suggestion
    return ApiEndpointsService.createUrlWithPathVariables(Uris.USERS.GROUP_LIST, [userId, 'groups']);
```

je pense que ça devrait fonctionner si tu mets juste ça

2021-12-09 20:41 UTC, matthieuaudemard commented on frontend-implicaction/src/app/core/services/api-endpoints.service.ts
> +    return ApiEndpointsService.createUrl(Uris.USERS.GROUP_SUBSCRIBE);
comme évoqué dans les fichiers du back, il faut utiliser une constante `Uris.GROUPS.SUBSCRIBE`

2021-12-09 20:41 UTC, matthieuaudemard commented on frontend-implicaction/src/app/discussion/components/top-group-listing/top-group-listing.component.html
> +          </ng-container>
je mettrais quand même bien juste un lien texte "rejoindre" le plus est pas très parlant. Tu peux mettre un classe `.overflow-ellipsis` sur le nom du groupe et lui fixer une taille maximale.

2021-12-09 20:41 UTC, matthieuaudemard commented on frontend-implicaction/src/app/discussion/components/top-group-listing/top-group-listing.component.ts
> +  subscribedGroups: string[] = [];
```suggestion
  userGroups: Group[] = [];
```

2021-12-09 20:41 UTC, matthieuaudemard commented on frontend-implicaction/src/app/discussion/components/top-group-listing/top-group-listing.component.ts
> +      .getAllGroups(this.currentUser.id)
```suggestion
      .getUserGroups(this.currentUser.id)
```

2021-12-09 20:41 UTC, matthieuaudemard commented on frontend-implicaction/src/app/discussion/components/top-group-listing/top-group-listing.component.ts
> +      );
Je comprend pas l'utilité de faire ça ? dans le pire des cas si tu veux récupérer seulement le nom d'un groupe utilise la fonction `.map(group  => group.name)`

2021-12-09 20:41 UTC, matthieuaudemard commented on frontend-implicaction/src/app/discussion/components/top-group-listing/top-group-listing.component.ts
> +        },
Si on considère la modif que j'ai proposée dans le back, plutôt que de renvoyé un groupe unique on renvoit la liste des groupes de l'utilisateur :

```suggestion
      .subscribe(
        groups => {
          this.toasterService.success('Succès', `Vous avez adhéré au groupe ${group.name}`);
          this.userGroups = groups;
        },
```

2021-12-09 20:41 UTC, matthieuaudemard commented on frontend-implicaction/src/app/discussion/components/top-group-listing/top-group-listing.component.ts
> +  loadData(): void {
tu n'as plus besoin de cette méthode donc tu peux reporter son corps dans le ngOnInit

2021-12-09 20:41 UTC, matthieuaudemard commented on frontend-implicaction/src/app/shared/models/uris.ts
> +    static readonly SUBSCRIBE_GROUP = 'subscribe';
à déplacer dans les constantes de groupe : /groups/:groupName/subsribe

2021-12-11 17:04 UTC, matthieuaudemard requested changes

2021-12-11 17:04 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/UserService.java
> +                .orElseThrow(() -> new UserNotFoundException("No user found with id " + userId));
utiliser la constante pour le message de userNotFound

2021-12-11 21:28 UTC, matthieuaudemard approved these changes
c'est d'la 💣

2021-12-11 23:01 UTC, matthieuaudemard approved these changes
🍾

2021-12-11 23:04 UTC, merged