RI-203: permet de valider une offre et un groupe
dyno-nuggets/refonte-implicaction pull request #211
Opened 2021-12-08 22:29 UTC by mathusha-sdv

* la validation des offres fonctionne
* problème quand j'utilise deux paginate dans une même page, le paginate.content est le même pour les deux. Ils récupèrent d'abord l'utilisateur puis les offres du coup ça ne s'affiche pas correctment
![image](https://user-images.githubusercontent.com/85649177/145298051-ccf9517b-dc4b-41e4-adfa-df283fa6882f.png)

2021-12-11 12:46 UTC, mathusha-sdv commented
J'ai ajouté des tests :) la validation fonctionne mais dès que j'essaie de récupérer le champ utilisateur du groupe ça casse tout :/

2021-12-11 17:55 UTC, matthieuaudemard requested changes

2021-12-11 17:55 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/SubredditAdapter.java
> +                .userId(model.getUser().getId())
hmmm peut être vérifier que c'est pas null avant.... on sait jamais

2021-12-11 17:55 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/GroupController.java
> +    @GetMapping(ACTIVE_GROUPS)
```suggestion
    @GetMapping(VALID_GROUPS)
```

2021-12-11 17:55 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/GroupController.java
> +    public ResponseEntity<Page<GroupDto>> getAllActiveGroups(
```suggestion
    public ResponseEntity<Page<GroupDto>> getAllValidGroups(
```

2021-12-11 17:55 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/JobPostingRepositoryCustom.java
> +     * @param active
juste rajouté un commentaire pour ce paramètre

2021-12-11 17:55 UTC, matthieuaudemard commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/GroupAdapterTest.java
> +                .ignoringFields("user", "posts", "numberOfPosts", "imageUrl", "username", "userId")
ici tu peux aussi vérifier la validité des champs username et userId avec un assert

2021-12-11 17:55 UTC, matthieuaudemard commented on frontend-implicaction/src/app/admin/jobs/components/pending-job-table/pending-job-table.component.ts
> +        },
```suggestion
        () => this.paginate({first: this.pageable.first, rows: this.pageable.rows}),
```

2021-12-11 17:55 UTC, matthieuaudemard commented on frontend-implicaction/src/app/admin/jobs/components/pending-job-table/pending-job-table.component.ts
> +  sortDirection = SortDirectionEnum;
On les utilise quelque part ces variables ? sinon 🧹

2021-12-11 19:46 UTC, mathusha-sdv commented on backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/GroupAdapterTest.java
> +                .ignoringFields("user", "posts", "numberOfPosts", "imageUrl", "username", "userId")
je peux pas pcq ça vérifie de facon récursive et l'utilisateur n'est pas récupéré au niveau du Group, a l'inverse du GroupDto

2021-12-11 20:09 UTC, matthieuaudemard requested changes

2021-12-11 20:09 UTC, matthieuaudemard commented on frontend-implicaction/src/app/core/services/api-endpoints.service.ts
> +  getAllActiveJobEndpoint(pageable: Pageable, criteria: JobCriteriaFilter, archive: any) {
```suggestion
  getAllActiveJobEndpoint(pageable: Pageable, criteria: JobCriteriaFilter, archive: any): string {
```
devrait corriger ton problème de ci

2021-12-11 21:26 UTC, matthieuaudemard requested changes
2 minuscules modifs et c'est tout bon ;)

2021-12-11 21:26 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/utils/ApiUrls.java
> +    public static final String VALIDATED_GROUPS_URI = "/validated";
```suggestion
    public static final String GET_VALIDATED_GROUPS_URI = "/validated";
```

2021-12-11 21:26 UTC, matthieuaudemard commented on frontend-implicaction/src/app/admin/groups/pending-group-table/pending-group-table.component.ts
> +        },
sur une seule ligne stp

2021-12-11 21:26 UTC, matthieuaudemard commented on frontend-implicaction/src/app/admin/jobs/components/pending-job-table/pending-job-table.component.ts
> +        () => this.paginate({first: this.pageable.first, rows: this.pageable.rows}),
normalement tu peux lui passer direct pageable : 
```suggestion
        () => this.paginate(this.pageable),
```

2021-12-11 23:54 UTC, matthieuaudemard commented on frontend-implicaction/src/app/shared/models/uris.ts
> +    static readonly VALIDATE_GROUP = 'groups/validate';
C'est quoi du coup la différence entre les 2 ?

2021-12-11 23:54 UTC, matthieuaudemard approved these changes

2021-12-12 13:02 UTC, mathusha-sdv commented on frontend-implicaction/src/app/shared/models/uris.ts
> +    static readonly VALIDATE_GROUP = 'groups/validate';
un vestige du rebase !

2021-12-12 13:04 UTC, matthieuaudemard commented on frontend-implicaction/src/app/shared/models/uris.ts
> +    static readonly VALIDATE_GROUP = 'groups/validate';
Du coup pour moi tu peux merge dès que les tests sont passés

2021-12-12 13:05 UTC, merged