RI-211 : affiche les dernières offres, les derniers posts et les derniers événements en page d'accueil
dyno-nuggets/refonte-implicaction pull request #215
Opened 2021-12-11 19:24 UTC by dylanbrudey

![RI_211_0](https://user-images.githubusercontent.com/47382098/145689003-cc07df6f-9be2-43d7-8b26-5c5926ae773b.gif)

2021-12-11 19:29 UTC, dylanbrudey commented on frontend-implicaction/src/app/home/components/job-list/job-list.component.html
> +<!--                 }"-->
A supprimer

2021-12-11 19:29 UTC, dylanbrudey commented on frontend-implicaction/src/app/home/components/job-list/job-list.component.scss
> +  //height: 21rem;
🗑️

2021-12-11 19:29 UTC, dylanbrudey commented on frontend-implicaction/src/app/home/components/post-card/post-card.component.scss
> +  //background-color: #f6f8ff;
🗑️

2021-12-11 19:29 UTC, dylanbrudey commented on frontend-implicaction/src/app/home/components/post-card/post-card.component.scss
> +
css dupliqué avec event-card et job-card de l'accueil

2021-12-11 19:29 UTC, dylanbrudey commented on frontend-implicaction/src/app/home/components/post-list/post-list.component.html
> +
space

2021-12-11 19:29 UTC, dylanbrudey commented on frontend-implicaction/src/app/home/components/event-card/event-card.component.ts
> +  // Should take a real Event object when ready
Input et commentaires à supprimer, ici à fin de tests

2021-12-11 20:22 UTC, matthieuaudemard requested changes

2021-12-11 20:22 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/PostService.java
> +        return returnList;
`return postRepo.findAll(Pageable.of(0, postCount, Sort.by(Sort.Direction.Desc, "createdAt")).map(....)`

2021-12-11 20:22 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/PostService.java
> +    public List<PostResponse> getLastPosts(int postCount) {
latests ?

2021-12-12 20:44 UTC, matthieuaudemard approved these changes
🍾

2021-12-12 20:51 UTC, merged