feat(user/profile): affiche les expériences professionnelles
dyno-nuggets/refonte-implicaction pull request #64
Opened 2021-09-09 21:45 UTC by M3L-DC

2021-09-09 23:16 UTC, matthieuaudemard requested changes
J'ai laissé quelques remarques :) certaines sont juste des suggestions, d'autres des simplifications.

Bon courage ;)

PS : comme vu avec @M3L-DC il faut tester avec de vraies données venant de notre base de données.

2021-09-09 23:16 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/profile/profile.component.scss
> +}
bootstrap te propose la class `.align-middle` => 🧹

2021-09-09 23:16 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/profile/profile.component.scss
> +  color: $primary;
bootstrap te propose la classe `.text-primary` => 🧹

2021-09-09 23:16 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/profile/profile.component.scss
> +  padding-left: 0.5rem;
c'est équivalent à `.ps-2` si je dis pas de connerie 😅 => 🧹

2021-09-09 23:16 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/profile/components/user-info-display/user-info-display.component.scss
> +@import "src/app/user/profile/profile.component";
cf plus bas mais on peut supprimer cet import en utilisant les classes bootstrap fournies

2021-09-09 23:16 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/profile/components/personal-card/personal-card.component.scss
> +@import "src/app/user/profile/profile.component";
cf plus bas, mais on peut supprimer cet important grâce aux classes bootstrap

2021-09-09 23:16 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/profile/components/work-experience-detail/work-experience-detail.component.html
> +  <p class="description-color">{{workExperience.description}}</p>
je pensais plutôt à quelque chose du genre :

```suggestion
<div class="mb-2 description">
  <p>{{workExperience.description}}</p>
```
et du coup définir la règle

```css
.description p {
 color: .... 
}
```

2021-09-10 14:05 UTC, dylanbrudey commented on frontend-implicaction/src/app/shared/models/uris.ts
> +    static readonly USER_BY_ID = 'users';
On avait choisi `USER_BY_ID` pour que ce soit clair, mais je pense que `BY_ID` parle aussi de lui-même, se trouvant déjà dans la classe `USERS`. Il est aussi au singulier donc pas de doute qu'on parle d'un User.

2021-09-10 22:16 UTC, matthieuaudemard requested changes
Allez on y est presque :)

2021-09-10 22:16 UTC, matthieuaudemard commented on frontend-implicaction/src/app/app-routing.module.ts
> +    path: 'user', loadChildren: () => import('./user/user.module').then(m => m.UserModule),
Vous pourriez mettre le loadChildren à la ligne stp ?

2021-09-10 22:16 UTC, matthieuaudemard commented on frontend-implicaction/src/app/icons/icons.module.ts
> +  Bell, Briefcase,
Mettre à la ligne

2021-09-10 22:16 UTC, matthieuaudemard commented on frontend-implicaction/src/app/icons/icons.module.ts
> +  User, Users
Mettre à la ligne

2021-09-10 22:16 UTC, matthieuaudemard commented on frontend-implicaction/src/app/shared/components/header/header.component.html
> +          </a>*
Pourquoi une étoile ?

2021-09-10 22:16 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/profile/components/work-experience-detail/work-experience-detail.component.html
> +<!--    <i-feather name="Briefcase" class="w-75 h-75 icon text-primary"></i-feather>-->
supprimer le commentaire

2021-09-10 22:16 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/profile/profile.component.scss
> +@import "src/assets/variables";
Pas besoin de l'import

2021-09-10 22:16 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/profile/profile.component.ts
> +import {ActivatedRoute} from "@angular/router";
changer en simple quote

2021-09-10 22:22 UTC, matthieuaudemard approved these changes
🥇 👍 💯 🍾

2021-09-10 22:24 UTC, merged