RI-31: sauvergarde les modifications apportées aux expériences professionelles
dyno-nuggets/refonte-implicaction pull request #87
Opened 2021-09-20 12:36 UTC by PaFlu-SDV

2021-09-20 15:03 UTC, mathusha-sdv approved these changes

2021-09-20 17:47 UTC, matthieuaudemard requested changes
Pas de changement violent à faire, juste un peu de renommage 👍

2021-09-20 19:52 UTC, matthieuaudemard commented
En fait plus j'y reflechis moins je trouve logique d'uilitser cette route et controller ... ça me parait plus cohérent de partir sur `/api/users/{userId}/experiences/` Est-ce que tu pourrais faire cette modification stp ? Du coup :
 * ajouter `/{userId}/experiences` dans le UserController
 * supprimer le WorkExperienceController

et du coup faire pareil pour les trainings. Par contre il faut garder les services / adapters / repository

2021-09-21 07:32 UTC, matthieuaudemard approved these changes
🦾

2021-09-21 07:35 UTC, merged