RI-26: Supprimer des expériences (dans le mode édition)
dyno-nuggets/refonte-implicaction pull request #94
Opened 2021-09-22 16:24 UTC by M3L-DC

On peut dès a présent supprimer un élément de la liste des expériences en cliquant sur la corbeille puis en cliquant sur save.
Dans le cas ou on rollback l'expérience n'est pas supprimé.

![GIF 22-09-2021 18-21-43](https://user-images.githubusercontent.com/36151209/134383137-ff245be2-ec9f-42ee-942f-09d48aaa5d9f.gif)

2021-09-22 16:53 UTC, matthieuaudemard requested changes
Juste quelques suppression pour le guid et quelques corrections mineurs sinon gg 😉

2021-09-22 16:53 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.html
> +      <label [for]="guid" class="form-label px-4">Description</label>
du coup on oublie cette histoire de guid. Tu peux supprimer et la classe utils et l'attribut guid et [for] et [id]

2021-09-22 16:53 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.html
> +        [id]="guid"
à supprimer donc

2021-09-22 16:53 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.html
> +        [inputStyleClass]="'form-control form-control-lg rounded-pill px-4 w-100'"
il est vraiment utile le w-100 du coup après la modif du p-calendar ?

2021-09-22 16:53 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.ts
> +    guid = Utils.generateGuid();
🗑️

2021-09-22 16:53 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.ts
> +        this.onDelete.next(experience);
👏

2021-09-22 16:53 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/experience-list/experience-list.component.ts
> +    // compare champ par champ les element de la liste avec l'expérience a supprimer et on recupère l'id dans la liste
```suggestion
    // compare champ par champ les éléments de la liste avec l'expérience a supprimer et on recupère l'id dans la liste
```

💋

2021-09-22 20:14 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.scss
> +    display: flex !important;
On avait pas mis en `display: block` ?

2021-09-23 07:18 UTC, M3L-DC commented on frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.html
> +        [inputStyleClass]="'form-control form-control-lg rounded-pill px-4 w-100'"
je vais jeter un œil

2021-09-23 07:19 UTC, M3L-DC commented on frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.ts
> +        this.onDelete.next(experience);
Bravo a toi plutôt x)

2021-09-23 07:27 UTC, M3L-DC commented on frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.ts
> +    guid = Utils.generateGuid();
Du coup, je dégage aussi le fichier Utils ?

2021-09-23 07:36 UTC, M3L-DC commented on frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.scss
> +    display: flex !important;
je viens de regarder et pour le coup on a du le remplacer par du flex pour ne pas avoir ca
![image](https://user-images.githubusercontent.com/36151209/134470216-22eec630-4ee1-4845-b432-2574f604b340.png)

2021-09-23 07:53 UTC, matthieuaudemard requested changes
Un tout p'tit espace à supprimer :)

2021-09-23 07:53 UTC, matthieuaudemard commented on frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.html
> +        class=" form-control w-100 px-4 text-description"
```suggestion
        class="form-control w-100 px-4 text-description"
```

2021-09-23 09:06 UTC, matthieuaudemard requested changes
Un p'tit espace qui fait mal 😢

2021-09-23 10:05 UTC, matthieuaudemard approved these changes

2021-09-23 10:12 UTC, merged